[package]
name = "hdos_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.0"
actix-web-validator = "5.0.1"
chrono = "0.4.23"
dotenv = "0.15.0"
futures = "0.3.25"
futures-util = "0.3.26"
handlebars = "4.3.6"
jsonwebtoken = "8.2.0"
lettre = "0.10.1"
mongodb = "2.3.1"
r2d2 = "0.8.10"
r2d2-mongodb = "*"
regex = "1.7.1"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
validator = {version ="0.16.0", features = ["derive"] }
